config/routes.rb
Rails.application.routes.draw do

namespace :admin do

  get "/" => 'base#index'
  resources :books
  end

  root 'books#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :books
  resources :users

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin/applications_controller.rb
class Admin::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

layout "admin" #rails will look for a views/layout/admin file
							 #gives us a separate layout for admin vs. client side
						   #see views/layouts/admin.html.erb

	def index

	end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    @book.each do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :description)
    end
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :autho, :price)
    end
end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @users = User.where(username: params[:username]).first
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome to the site!'
      redirect_to root_path
    else
      flash[:alert] = 'Oops! Incorrect username or password'
      render :new
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

<p>Title<br>
<%= f.text_field :title %>
</p>

<p>Author<br>
<%= f.text_field :author %>
</p>

<%= f.submit 'Save Changes' %>

<% end %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/admin/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books in stock</h1>

<table class="table table-bordered">

  <thead>
    <tr>
      <th>Book</th>
      <th>Author</th>
      <th>Price</th>
      <th>More info</th>
    </tr>
  </thead>

  <tbody>
      <% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
        <td><%= link_to 'Edit', books_path(book.id) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tbody>
  <%= link_to 'Add new book', new_book_path %>

</table>

app/views/admin/books/new.html.erb
<h1>New Book</h1>

<%= form_for(@book) do |f| %>

<p>Title<br>
<%= f.text_field :title %>
</p>

<p>Author<br>
<%= f.text_field :author %>
</p>


<%= f.submit 'Add Book' %>

<% end %>

<%= link_to 'Back', books_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<%= link_to('Admin', admin_path) %>
<p id="notice"><%= notice %></p>

<h1>Books in stock</h1>

<table class="table table-bordered">

  <thead>
    <tr>
      <th>Book</th>
      <th>Author</th>
      <th>Price</th>
      <th>More info</th>
    </tr>
  </thead>

  <tbody>
      <% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td><%= link_to 'Show', book_path(book.id) %></td>
      <% end %>
    </tr>
  </tbody>


</table>

app/views/books/show.html.erb
<p>
<%= @book.title %><br>
<%= @book.author %><br>
</p>

<p>Description:
</p>


<%= link_to 'Back', books_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- admin home page -->

<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= link_to('Books', books_path) %>
  <%= link_to('Logout', '') %>

  <%= link_to('Login', '') %>
  <%= link_to('Sign Up!', '') %>
</header>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- public home page -->

<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>

</header>

<%= yield %>

</body>
</html>